import assert from "node:assert/strict";
import test from "node:test";

import { parseCargoLockPackageVersion } from "./desktop-version.mjs";

const cargoLock = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "rhelo-helper"
version = "9.9.9"

[[package]]
name = "rhelo"
version = "0.1.1"
dependencies = [
 "serde",
]
`;

test("reads the exact Rhelo package version from LF Cargo.lock data", () => {
  assert.equal(parseCargoLockPackageVersion(cargoLock, "rhelo"), "0.1.1");
});

test("reads the exact Rhelo package version from CRLF Cargo.lock data", () => {
  const crlfCargoLock = cargoLock.replace(/\n/g, "\r\n");
  assert.equal(parseCargoLockPackageVersion(crlfCargoLock, "rhelo"), "0.1.1");
});

test("does not match a similarly named dependency", () => {
  assert.equal(parseCargoLockPackageVersion(cargoLock, "rhelo-helper"), "9.9.9");
  assert.equal(parseCargoLockPackageVersion(cargoLock, "rhel"), undefined);
});
