export interface BibleBook {
  code: string;
  name: string;
  testament: string;
  chapters: number;
}

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { code: "GEN", name: "Genesis", testament: "OT", chapters: 50 },
  { code: "EXO", name: "Exodus", testament: "OT", chapters: 40 },
  { code: "LEV", name: "Leviticus", testament: "OT", chapters: 27 },
  { code: "NUM", name: "Numbers", testament: "OT", chapters: 36 },
  { code: "DEU", name: "Deuteronomy", testament: "OT", chapters: 34 },
  { code: "JOS", name: "Joshua", testament: "OT", chapters: 24 },
  { code: "JDG", name: "Judges", testament: "OT", chapters: 21 },
  { code: "RUT", name: "Ruth", testament: "OT", chapters: 4 },
  { code: "1SA", name: "1 Samuel", testament: "OT", chapters: 31 },
  { code: "2SA", name: "2 Samuel", testament: "OT", chapters: 24 },
  { code: "1KI", name: "1 Kings", testament: "OT", chapters: 22 },
  { code: "2KI", name: "2 Kings", testament: "OT", chapters: 25 },
  { code: "1CH", name: "1 Chronicles", testament: "OT", chapters: 29 },
  { code: "2CH", name: "2 Chronicles", testament: "OT", chapters: 36 },
  { code: "EZR", name: "Ezra", testament: "OT", chapters: 10 },
  { code: "NEH", name: "Nehemiah", testament: "OT", chapters: 13 },
  { code: "EST", name: "Esther", testament: "OT", chapters: 10 },
  { code: "JOB", name: "Job", testament: "OT", chapters: 42 },
  { code: "PSA", name: "Psalms", testament: "OT", chapters: 150 },
  { code: "PRO", name: "Proverbs", testament: "OT", chapters: 31 },
  { code: "ECC", name: "Ecclesiastes", testament: "OT", chapters: 12 },
  { code: "SNG", name: "Song of Solomon", testament: "OT", chapters: 8 },
  { code: "ISA", name: "Isaiah", testament: "OT", chapters: 66 },
  { code: "JER", name: "Jeremiah", testament: "OT", chapters: 52 },
  { code: "LAM", name: "Lamentations", testament: "OT", chapters: 5 },
  { code: "EZK", name: "Ezekiel", testament: "OT", chapters: 48 },
  { code: "DAN", name: "Daniel", testament: "OT", chapters: 12 },
  { code: "HOS", name: "Hosea", testament: "OT", chapters: 14 },
  { code: "JOL", name: "Joel", testament: "OT", chapters: 3 },
  { code: "AMO", name: "Amos", testament: "OT", chapters: 9 },
  { code: "OBD", name: "Obadiah", testament: "OT", chapters: 1 },
  { code: "JON", name: "Jonah", testament: "OT", chapters: 4 },
  { code: "MIC", name: "Micah", testament: "OT", chapters: 7 },
  { code: "NAM", name: "Nahum", testament: "OT", chapters: 3 },
  { code: "HAB", name: "Habakkuk", testament: "OT", chapters: 3 },
  { code: "ZEP", name: "Zephaniah", testament: "OT", chapters: 3 },
  { code: "HAG", name: "Haggai", testament: "OT", chapters: 2 },
  { code: "ZEC", name: "Zechariah", testament: "OT", chapters: 14 },
  { code: "MAL", name: "Malachi", testament: "OT", chapters: 4 },
  // New Testament
  { code: "MAT", name: "Matthew", testament: "NT", chapters: 28 },
  { code: "MRK", name: "Mark", testament: "NT", chapters: 16 },
  { code: "LUK", name: "Luke", testament: "NT", chapters: 24 },
  { code: "JHN", name: "John", testament: "NT", chapters: 21 },
  { code: "ACT", name: "Acts", testament: "NT", chapters: 28 },
  { code: "ROM", name: "Romans", testament: "NT", chapters: 16 },
  { code: "1CO", name: "1 Corinthians", testament: "NT", chapters: 16 },
  { code: "2CO", name: "2 Corinthians", testament: "NT", chapters: 13 },
  { code: "GAL", name: "Galatians", testament: "NT", chapters: 6 },
  { code: "EPH", name: "Ephesians", testament: "NT", chapters: 6 },
  { code: "PHP", name: "Philippians", testament: "NT", chapters: 4 },
  { code: "COL", name: "Colossians", testament: "NT", chapters: 4 },
  { code: "1TH", name: "1 Thessalonians", testament: "NT", chapters: 5 },
  { code: "2TH", name: "2 Thessalonians", testament: "NT", chapters: 3 },
  { code: "1TI", name: "1 Timothy", testament: "NT", chapters: 6 },
  { code: "2TI", name: "2 Timothy", testament: "NT", chapters: 4 },
  { code: "TIT", name: "Titus", testament: "NT", chapters: 3 },
  { code: "PHM", name: "Philemon", testament: "NT", chapters: 1 },
  { code: "HEB", name: "Hebrews", testament: "NT", chapters: 13 },
  { code: "JAS", name: "James", testament: "NT", chapters: 5 },
  { code: "1PE", name: "1 Peter", testament: "NT", chapters: 5 },
  { code: "2PE", name: "2 Peter", testament: "NT", chapters: 3 },
  { code: "1JN", name: "1 John", testament: "NT", chapters: 5 },
  { code: "2JN", name: "2 John", testament: "NT", chapters: 1 },
  { code: "3JN", name: "3 John", testament: "NT", chapters: 1 },
  { code: "JUD", name: "Jude", testament: "NT", chapters: 1 },
  { code: "REV", name: "Revelation", testament: "NT", chapters: 22 },
];

export function getBookName(code: string): string {
  return BIBLE_BOOKS.find(b => b.code === code)?.name || code;
}
